name: PHP Composer

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Change path
      run: cd /var/www/html/nigp
      
    - name: run composer update
      run: composer install
    
    - name: run script
      run: cd /var/www/html/ && ./script.sh
      
