name: PHP Composer

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Composer update
      run: cd /var/www/html && sudo apt-get install mysql-server -y
      
    - name: run script
      run: .././script.sh
