name: PHP Composer

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: self-hosted

    steps:

    - name: Composer update
      run: composer update
      
    - name: run script
      run: .././script.sh
