name: PHP Composer

on:
  push:
    branches:  develop 
  pull_request:
    branches:  develop 
  schedule:
  - cron: "* * * * 1-7"
  name: Install Dependencies
  run:  cd /var/www/html/develop
        git pull origin develop
       
